### ISSUE TITLE
[Administración y programación de Base de Datos] Ex-Control 1

### ISSUE THREAD

**Issue by MarceloPazPezo** [MarceloPazPezo/MyRepo#4]
[Ex-Control-1](https://github.com/MarceloPazPezo/MyRepo/blob/main/Icinf/Semestre%207/Administración%20y%20Programación%20de%20Base%20de%20Datos/Guia%20de%20ejercicios%20(ExControl%201)/ExControl-1.pdf)

- [x] Ejercicio 1.
- [x] Ejercicio 2.
- [x] Ejercicio 3.
- [x] Ejercicio 4.
- [x] Ejercicio 5.
- [x] Ejercicio 6.
- [x] Ejercicio 7.
- [x] Ejercicio 8.
- [x] Ejercicio 9.
- [x] Ejercicio Bonus.
- [x] Investigar sobre grados dentro de un árbol binario.

**Comment by MarceloPazPezo** [comment]
Terminar ejercicio 7, 8, 9 y 10.

**Comment by NicoGomezM** [comment]
q paja xd
